Genepop 4.8.2: Hardy-Weinberg test

File: sample.txt (Title line: "Grape populations in southern France")

Number of populations detected:    4
Number of loci detected:           6


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************


==========================================
     Results by locus
==========================================


Locus "ADH Locus 1"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Grange des  0.8717  0.0028  -0.1852 -0.2125  19431 switches
Tertre Rot  1.0000  0.0000  -0.6000 -0.6250  42994 switches
Bonneau 05   - 
last pop     - 

Locus "ADH #2"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Grange des  0.2132  0.0050   0.2941  0.2500  14462 switches
Tertre Rot  0.3978  0.0045   0.1429  0.1625  19479 switches
Bonneau 05  0.6189  0.0019   0.2727  0.3125  42818 switches
last pop    1.0000  0.0000  -1.0000 -1.0000  31422 switches

Locus "ADH three"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Grange des  0.6193  0.0019   0.2727  0.3125  43015 switches
Tertre Rot  1.0000  0.0000  -0.3333 -0.2500  16113 switches
Bonneau 05  1.0000  0.0000  -0.2800 -0.1250   6646 switches
last pop    0.0843  0.0014   1.0000  1.3333  31509 switches

Locus "ADH-4"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Grange des  0.3951  0.0037   0.1429  0.1625  19548 switches
Tertre Rot  0.2091  0.0034   0.3846  0.5000  16032 switches
Bonneau 05  0.6208  0.0023   0.2727  0.3125  42620 switches
last pop    1.0000  0.0000  -0.2000 -0.2222  10576 switches

Locus "ADH-5"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Grange des  0.6217  0.0016   0.2727  0.3125  42756 switches
Tertre Rot  1.0000  0.0000  -0.1429 -0.1000   4693 switches
Bonneau 05  0.4926  0.0046  -0.1429  0.1250  22329 switches
last pop    1.0000  0.0000  -0.3333 -0.3750  19903 switches

Locus "mtDNA" not diploid.
-----------------------------------------

==========================================
     Results by population
==========================================


Pop : Grange des Peres  
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
ADH Locus   0.8717  0.0028  -0.1852 -0.2125  19431 switches
ADH #2      0.2132  0.0050   0.2941  0.2500  14462 switches
ADH three   0.6193  0.0019   0.2727  0.3125  43015 switches
ADH-4       0.3951  0.0037   0.1429  0.1625  19548 switches
ADH-5       0.6217  0.0016   0.2727  0.3125  42756 switches

Pop : Tertre Roteboeuf 
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
ADH Locus   1.0000  0.0000  -0.6000 -0.6250  42994 switches
ADH #2      0.3978  0.0045   0.1429  0.1625  19479 switches
ADH three   1.0000  0.0000  -0.3333 -0.2500  16113 switches
ADH-4       0.2091  0.0034   0.3846  0.5000  16032 switches
ADH-5       1.0000  0.0000  -0.1429 -0.1000   4693 switches

Pop : Bonneau 05   
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
ADH Locus    No information. 
ADH #2      0.6189  0.0019   0.2727  0.3125  42818 switches
ADH three   1.0000  0.0000  -0.2800 -0.1250   6646 switches
ADH-4       0.6208  0.0023   0.2727  0.3125  42620 switches
ADH-5       0.4926  0.0046  -0.1429  0.1250  22329 switches

Pop : last pop
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
ADH Locus    No information. 
ADH #2      1.0000  0.0000  -1.0000 -1.0000  31422 switches
ADH three   0.0843  0.0014   1.0000  1.3333  31509 switches
ADH-4       1.0000  0.0000  -0.2000 -0.2222  10576 switches
ADH-5       1.0000  0.0000  -0.3333 -0.3750  19903 switches

Normal ending
